---
- hosts: "hsd_drp"     #DO NOT USE "all", otherwise every computer in the network will be used
  become: true         #in order to run as root use the "-K" option in the command line
  gather_facts: false
  strategy: free
  ignore_errors: true  #needs to be true, oherwise the program stops when an error occurs
  check_mode: true     #modify to false, this is a failsafe
  
  tasks:
   - name: "install driver"
     ansible.builtin.shell: |
       rmmod datadev
       systemctl disable irqbalance.service
       systemctl daemon-reload 
       systemctl start kcu.service
       systemctl enable kcu.service
 
