---
- hosts: "timing_drp"    # timing_high, wave8_drp,camlink_drp,hsd_drp
  become: false       #do not use root
  gather_facts: false
  ignore_errors: true
  check_mode: true    #failsafe, set to false if you want to run it
  serial: 1
  vars:
    filepath:      "~psrel/git/daqnodeconfig/mcs/drp/"
    firmw:         "DrpTDet-0x04000300-20240129134456-weaver-e052f59_primary.mcs"
    setup_source:  "source ~tmoopr/daq/setup_env.sh"
    cd_cameralink: "cd ~psrel/git/pgp-pcie-apps/software/"
    

  tasks:
  - name: "update firmware"
    shell:
    args:
      cmd: nohup xterm -hold -T {{ inventory_hostname }} -e "bash -c '{{ setup_source }} ; {{ cd_cameralink }} ; python ./scripts/nodePcieFpga.py --dev /dev/datadev_1  --filename {{ filepath }}{{ firmw }} '" </dev/null >/dev/null 2>&1 &
      executable: /bin/bash  


