---
- hosts: "wave8_drp"    #DO NOT USE "all", otherwise every computer in the network will be used
  become: true        #in order to run as root use the "-K" option in the command line
  gather_facts: false
  strategy: free      #Allows to run in parallel on several nodes
  ignore_errors: true #needs to be true, oherwise the program stops when an error occurs
  check_mode: false    #modify to false, this is a failsafe
  vars:
    hsd_files: 
    - {src: '../../shared_files/datadev.ko_srcf',      dest: '/usr/local/sbin/datadev.ko',          mode: a+x}
    - {src: '../../shared_files/kcuSim',               dest: '/usr/local/sbin/kcuSim',              mode: a+x}
    - {src: '../../shared_files/kcuStatus',            dest: '/usr/local/sbin/kcuStatus',           mode: a+x}
    - {src: '../../shared_files/kcu.service',          dest: '/usr/lib/systemd/system/kcu.service', mode: a}
    - {src: '../../shared_files/sysctl.conf',          dest: '/etc/sysctl.conf',                    mode: a}

  tasks:

  - name: "copy files"
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      backup: true
      mode: "{{ item.mode }}"
    with_items: "{{ hsd_files }}" 
 
    
