---
- hosts: "wave8_drp"    # timing_high, wave8_drp,camlink_drp,hsd_drp
  become: false       #do not use root
  gather_facts: false
  ignore_errors: true
  check_mode: false    #failsafe, set to false if you want to run it
  serial: 1
  vars:
    filepath:      "~weaver/mcs/drp/"
    firmw:         "XilinxKcu1500Pgp4_10Gbps-0x02050000-20240819125301-weaver-fe20e21_primary.mcs"
    setup_source:  "source ~tmoopr/daq/setup_env.sh"
    cd_cameralink: "cd ~melchior/git/pgp-pcie-apps/software/"
    

  tasks:
  - name: "update firmware"
    shell:
    args:
      cmd: nohup xterm -hold -T {{ inventory_hostname }} -e "bash -c '{{ setup_source }} ; {{ cd_cameralink }} ; python ./scripts/nodePcieFpga.py --dev /dev/datadev_1  --filename {{ filepath }}{{ firmw }} '" </dev/null >/dev/null 2>&1 &
      executable: /bin/bash  


