---
# in order to run this script, make sure that kinit is activated

- hosts: "tmo_hsd"    # timing_high, wave8_drp,camlink_drp,hsd_drp
  become: false       #do not use root
  gather_facts: false
  ignore_errors: true #needs to be true, oherwise the program stops when an error occurs
  check_mode: false    #failsafe, set to false if you want to run it
  serial: 1
  vars:
    filepath:      "~weaver/mcs/hsd/"
    firmw:         "hsd_6400m-0x06000000-20240814101606-weaver-ae24264.mcs"
    setup_source:  "source ~tmoopr/daq/setup_env.sh"
    cd_cameralink: "cd ~melchior/git/pgp-pcie-apps/software/"
    TMO_HSDs:      ['1b','1a','3e','3d','01','da','b2','b1','89','88']

  tasks:
  - name: "update firmware"
    shell:
    args:
      cmd: nohup xterm -hold -T {{ inventory_hostname }} -e "bash -c '{{ setup_source }} ; {{ cd_cameralink }} ; python ./scripts/nodePcieFpga.py --dev /dev/datadev_{{ item }}  --filename {{ filepath }}{{ firmw }} '" </dev/null >/dev/null 2>&1 &
      executable: /bin/bash  
    with_items: "{{ TMO_HSDs }}"
