# This playbook reloads the datadev driver on the nodes. It should be run if datadev.service is already installed,
# otherwise run files_update.yml instead.
# The playbook checks for the presence of the service file and only proceeds with the driver reload if it exists.

# how to run the script
# ansible-playbook driver_reload.yml -K -e host='TMO_hsd_drp RIX_hsd_drp XPP_hsd_drp'

# RM 2026-03-11: Initial version

---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  ignore_errors: yes

  pre_tasks:
    - name: Assert required extra variables are defined
      ansible.builtin.assert:
        that:
          - host is defined and host | length > 0
        fail_msg: >
          A 'host' must be supplied as an
          extra variable (-e "host=...").

    - name: Get service status                        
      ansible.builtin.stat:
        path: /etc/systemd/system/datadev.service
      register: service_file_status

    - name: Abort if service not present
      ansible.builtin.fail:
        msg: "datadev.service not found. Please run files_update.yml instead."
      when: not service_file_status.stat.exists

  tasks:
    - name: Initial message
      ansible.builtin.debug:
        msg: "Reloading driver on {{ inventory_hostname }}"
                                                      

    - name: reload driver                             
      ignore_errors: true                             
      ansible.builtin.shell: |                        
        rmmod datadev 2>/dev/null || true             
        systemctl daemon-reload                       
        systemctl start datadev.service               
        systemctl enable datadev.service
      when: service_file_status.stat.exists           
                                                      
                                                      