# This playbook updates the firmware on the nodes. It should be run if datadev.service is already installed
# otherwise run files_update.yml before.

# how to run the script
# ansible-playbook firmware_update.yaml -e host='TMO_hsd_drp RIX_hsd_drp XPP_hsd_drp' -e firmware='hsd'


# RM 2026-03-11: Initial version

---
- hosts: "{{ host }}"
  gather_facts: false  # faster execution, we only need the distribution facts in the pre-tasks
  become: true         # become root 
  ignore_errors: yes # Allows playbook to continue to next host even if one fails (e.g., build error)
  vars:
    firmwares:
      hsd:          drp/DrpPgpIlv-0x05040300-20250811085728-weaver-846de54
      timing:       drp/DrpTDet-0x05040300-20250811085743-weaver-846de54
      timingC1100:  drp/DrpTDetGpuC1100-0x05040300-20250811100751-weaver-846de54
      wave:         drp/XilinxKcu1500Pgp4_6Gbps-0x02050000-20240215192118-ruckman-3e991ff
      camera:       drp/Lcls2XilinxKcu1500Pgp2b-0x03100000-20250114180154-ruckman-524f66a
      jungfrau:     drp/Lcls2XilinxKcu1500Udp_10GbE-0x03040000-20250314213558-ruckman-5042731
      epix:         drp/Lcls2XilinxKcu1500Pgp4_6Gbps-0x03080000-20240206001701-ruckman-9316db7
      
  pre-task:
  - name: Assert required extra variables are defined
    ansible.builtin.assert:
      that:
      - host is defined and host | length > 0
          - host is defined and host | length > 0
          - firmware is defined and firmware | length > 0
      fail_msg: >
        All 'host', 'host', and 'firmware' must be supplied as
        extra variables (-e "host=... firmware=...").

  - name: Using user defined firmware name
    ansible.builtin.set_fact:
      my_firm: "drp/{{ firmware }}"
    when: "{{ firmware }} not in firmwares"

  - name: Using firmware from list
    ansible.builtin.set_fact:
      my_firm: "{{ firmwares[firmware] }}"
    when: "{{ firmware }} in firmwares"    

  - name: Check if datadev_1 exists
    stat:
      path: /proc/datadev_1
    register: stat_result

  - name: use datadev_1
    set_fact:
      datadev: datadev_1
    when: stat_result.stat.exists

  - name: use datadev_0
    set_fact:  
      datadev: datadev_0
    when: not stat_result.stat.exists

  tasks:
  - name: Initial message
    ansible.builtin.debug:
      msg: "Installing new firmware for {{ firmware }}: {{ my_firm }} on {{ inventory_hostname }}"

  #updates the firmware, timeout 5 minutes 
  - name: update firmware
    become: true
    ignore_errors: true
       
    vars:
      filepath:      "/cds/home/p/psrel/mcs/"
      setup_source:  "source /cds/home/opr/tmoopr/daq/setup_env.sh"
      cd_cameralink: "cd /cds/home/p/psrel/git/pgp-pcie-apps/software/"
    register: firmware_log
    async: 300  # wait up to 5 minutes s
    poll: 5    # poll every 5 seconds
    
    ansible.builtin.shell:
      cmd: '{{ setup_source }} ; {{ cd_cameralink }} ; python ./scripts/updatePcieFpga.py --dev /dev/{{ datadev }}  --filename {{ filepath }}{{ my_firm }} --rescan False'
    changed_when: "'Firmware already' not in firmware_log.stdout_lines"
    notify: ipmi_reboot
    
 
  - name: Show build script output
    ansible.builtin.debug:
      msg: "{{ firmware_log.stdout_lines }}"

  handlers:
  # reset the node if firmware has been changed
  - name: ipmi_reboot    #IF firmware is updated, reset the node
    become: true         #in order to run as root use the "-K" option in the command line
    ignore_errors: true  #needs to be true, oherwise the program stops when an error occurs

    ansible.builtin.shell: |
      ipmitool power reset
    