# SRCF_manual.yml: Master update for all devices (driver, service, firmware and sysctl.conf)
# This playbook updates the driver, service, firmware and sysctl.conf on the nodes.

# How to run the script
# ansible-playbook srcf_manual.yaml -e host='TMO_hsd_drp RIX_hsd_drp XPP_hsd_drp' 
# -e driver='6.9.0' -e service='kcu_hsd' -e firmware='hsd'

# RM 2026-03-11: Initial version
--- 
- hosts: "{{ host }}"
  
  vars: 
    files_name: 
    - {src: '{{ path }}/datadev/datadev.ko_{{ driver }}_{{ linux_repo }}_{{ linux_version }}',            dest: '/usr/local/sbin/datadev.ko',           mode: a+x}
    - {src: '{{ path }}/services/{{ service }}.service',   dest: '/etc/systemd/system/datadev.service',  mode: a+r}
    - {src: '{{ path }}/sysctl.conf',                      dest: '/etc/sysctl.d/40-datadev-sysctl.conf', mode: a+r}
    
    firmware: drp/{{ firmware }}
  tasks: 
    - name: initial message
      ansible.builtin.debug:
        msg: Master update {{ driver }}, {{ service }}, {{ firmware }} and sysctl.conf on {{ inventory_hostname }}

    - name: load files
      include_tasks: files_update.yml
    
    - name: update firmware
      include_tasks: firmware_update.yml

