# This playbook updates the sysctl.conf on the nodes. 
# 
# how to run the script
# ansible-playbook sysctlOnly_update.yml -K -e host='TMO_hsd_drp RIX_hsd_drp XPP_hsd_drp'

# RM 2026-07-28: Initial version

---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  ignore_errors: yes

  vars: 
    path: "/sdf/home/p/psrel/ansible_files"
                                                         
  tasks:
    - name: initial message
      ansible.builtin.debug:
        msg: "Installing new sysctl.conf on {{ inventory_hostname }}"
                                                          
    - name: load files
      become: true
      ignore_errors: true
      ansible.builtin.copy:                               
        src: '{{ path }}/sysctl.conf'
        dest: '/etc/sysctl.d/90-daq.conf'
        mode: a+r
        backup: true
      notify: install drivers

  handlers:
   - name: install drivers
     ignore_errors: true
     ansible.builtin.shell: |
       sysctl -p /etc/sysctl.d/90-daq.conf    
                                               